name: Deploy from Zip

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Unzip
        run: sudo apt-get install -y unzip

      - name: Unzip content
        run: |
          # Ищем ZIP файл в репозитории и распаковываем его
          mkdir public
          # Укажите точное имя вашего файла вместо "game.zip"
          unzip "*.zip" -d public/
          
          # Если внутри ZIP есть лишняя вложенная папка, 
          # этот скрипт попробует вытащить index.html в корень
          if [ -f public/**/index.html ]; then
             cp public/**/index.html public/
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
